# Generated by Django 6.0.5 on 2026-06-10 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(default="default", max_length=40, unique=True),
                ),
                ("state", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SeasonRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("entry_fee", models.IntegerField(default=3000000)),
                ("champion_reward", models.IntegerField(default=20000000)),
                ("runner_up_reward", models.IntegerField(default=10000000)),
                ("third_reward", models.IntegerField(default=5000000)),
                ("weeks_in_demo", models.IntegerField(default=2)),
                ("max_games_in_demo", models.IntegerField(default=8)),
                ("meta", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("is_player", models.BooleanField(default=False)),
                ("funds", models.IntegerField(default=3000000)),
                ("recent_mood", models.IntegerField(default=60)),
                ("bond", models.IntegerField(default=70)),
                ("trust", models.IntegerField(default=70)),
                ("fairness", models.IntegerField(default=70)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("draws", models.IntegerField(default=0)),
                ("meta", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="GameRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("played_at", models.DateTimeField(auto_now_add=True)),
                ("home_score", models.IntegerField(default=0)),
                ("away_score", models.IntegerField(default=0)),
                ("result", models.CharField(max_length=20)),
                ("cold_game", models.BooleanField(default=False)),
                ("summary", models.JSONField(blank=True, default=dict)),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_games",
                        to="league.team",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_games",
                        to="league.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("name", models.CharField(max_length=80)),
                ("age", models.IntegerField()),
                ("job", models.CharField(max_length=40)),
                ("batting_role", models.CharField(max_length=40)),
                ("positions", models.JSONField(default=list)),
                ("primary_position", models.CharField(max_length=30)),
                ("batting_stats", models.JSONField(default=dict)),
                ("fielding_stats", models.JSONField(default=dict)),
                ("position_stats", models.JSONField(default=dict)),
                ("pitches", models.JSONField(blank=True, default=list)),
                ("max_stamina", models.IntegerField()),
                ("stamina", models.IntegerField()),
                ("condition", models.IntegerField(default=70)),
                ("attendance", models.IntegerField()),
                ("dues_trait", models.IntegerField()),
                ("sponsor_trait", models.IntegerField()),
                ("traits", models.JSONField(blank=True, default=list)),
                ("recent_games", models.JSONField(blank=True, default=list)),
                ("consecutive_starts", models.IntegerField(default=0)),
                ("missed_games", models.IntegerField(default=0)),
                ("considering_leave", models.BooleanField(default=False)),
                ("injured", models.BooleanField(default=False)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="league.team",
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "number")},
            },
        ),
    ]
