# Generated by Django 6.0.5 on 2026-06-10 17:03

import django.db.models.deletion
from django.db import migrations, models


def seed_skill_tables(apps, _schema_editor):
    from league.demo_data import BATTING_STRATEGY_DATA, PITCH_TYPE_DATA

    PitchType = apps.get_model("league", "PitchType")
    BattingStrategy = apps.get_model("league", "BattingStrategy")

    for code, data in PITCH_TYPE_DATA.items():
        PitchType.objects.update_or_create(
            code=code,
            defaults={
                "label": code,
                "speed_min": data["speed"][0],
                "speed_max": data["speed"][1],
                "contact_mod": data.get("contactMod", 0),
                "discipline_mod": data.get("disciplineMod", 0),
                "control_mod": data.get("controlMod", 0),
                "stamina": data.get("stamina", 1),
                "distance_mod": data.get("distanceMod"),
                "grounder": data.get("grounder"),
                "ground_distance_mod": data.get("groundDistanceMod"),
                "description": data["description"],
            },
        )

    for code, data in BATTING_STRATEGY_DATA.items():
        BattingStrategy.objects.update_or_create(code=code, defaults={**data})


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0003_player_batting_strategies"),
    ]

    operations = [
        migrations.CreateModel(
            name="BattingStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("label", models.CharField(max_length=60)),
                ("stamina", models.FloatField(default=1)),
                ("contact", models.FloatField(default=1)),
                ("power", models.FloatField(default=1)),
                ("discipline", models.FloatField(default=1)),
                ("speed", models.FloatField(default=1)),
                ("distance", models.FloatField(default=0)),
                ("description", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PitchType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("label", models.CharField(max_length=40)),
                ("speed_min", models.FloatField()),
                ("speed_max", models.FloatField()),
                ("contact_mod", models.FloatField(default=0)),
                ("discipline_mod", models.FloatField(default=0)),
                ("control_mod", models.FloatField(default=0)),
                ("stamina", models.FloatField(default=1)),
                ("distance_mod", models.FloatField(blank=True, null=True)),
                ("grounder", models.FloatField(blank=True, null=True)),
                ("ground_distance_mod", models.FloatField(blank=True, null=True)),
                ("description", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="gamerecord",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_records",
                to="league.demoaccount",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="league.demoaccount",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="league.demoaccount",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("account", "name"), name="unique_team_name_per_account"
            ),
        ),
        migrations.RunPython(seed_skill_tables, migrations.RunPython.noop),
    ]
